const events = {
  INCREMENTAR_MAN: "INCREMENTAR_MAN_EVENTO",
  DECREMENTAR_MAN: "DECREMENTAR_MAN_EVENTO",
  INCREMENTAR_WOMAN: "INCREMENTAR_WOMAN_EVENTO",
  DECREMENTAR_WOMAN: "DECREMENTAR_WOMAN_EVENTO",
  INCREMENTAR_CHILD: "INCREMENTAR_CHILD_EVENTO",
  DECREMENTAR_CHILD: "DECREMENTAR_CHILD_EVENTO",
  CALCULO_ENVIADO: "CALCULO_ENVIADO_EVENTO",
  CALCULO_RECEBIDO: "CALCULO_RECEBIDO_EVENTO",
  REGISTER: "CADASTRAR_EVENTO",
};
